# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/qgofertext',
                'doc_host': 'https://BDFL669.github.io',
                'git_url': 'https://github.com/BDFL669/qgofertext',
                'lib_path': 'qgofertext'},
  'syms': {'qgofertext.core': {'qgofertext.core.foo': ('core.html#foo', 'qgofertext/core.py')}}}
