# AUTOGENERATED! DO NOT EDIT! File to edit: ..\nbs\02_manage_index.ipynb.

# %% auto 0
__all__ = []

# %% ..\nbs\02_manage_index.ipynb 5
from qgoferutils.manage_index import create_index_list, process_index_list
