# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_search.ipynb.

# %% auto 0
__all__ = ['initialize_config', 'index_folders']

# %% ../nbs/02_search.ipynb 3
from pathlib import Path
from qgoferutils.config import QGoferConfig
from qgoferutils.manage_index import (
    create_index_list,
    process_index_list,
    destroy_index_list,
    create_qgofer_cache,
)

# %% ../nbs/02_search.ipynb 4
def initialize_config(
    home: Path = Path.home(), root_dir: Path = Path.home()
) -> QGoferConfig:
    """
    Args:
        home: The home directory of the user, defaults to Path.home(). The `home` path is where qgofer config data is stored
        root_dir: The root directory to index, defaults to Path.home(). The `root_dir`  is where qgofer searches.
    """
    q = QGoferConfig(home=home, root_dir=root_dir)
    return q

# %% ../nbs/02_search.ipynb 5
def index_folders(path: Path) -> None:
    """
    Args:
        path: The path provided is the patn which should be indexed.
    """
    create_index_list(path)
    create_qgofer_cache()
    process_index_list()
    destroy_index_list()
